02_first_step_with_django/example/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

02_first_step_with_django/example/myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views.testViews import TestView, TestResultView

app_name='myapp'
urlpatterns = [    
    path('', TestView.as_view(), name='index'),
    path('result/<str:task_id>/', TestResultView.as_view(), name='task_result'),
]

02_first_step_with_django/example/myapp/models.py
from django.db import models

# Create your models here.

02_first_step_with_django/example/myapp/views/testViews.py
from django.views import View
from ..tasks import test_task
from django.http import HttpResponse
from celery.result import AsyncResult
from django.shortcuts import render

class TestView(View):
    def get(self, request, *args, **kwargs):
        aresult = test_task.delay(1,2)        
        context={}
        context['task_id'] = aresult.id
        print(aresult.id)                
        return render(request, 'myapp/index.html', context=context)
    
class TestResultView(View):
    def get(self, request, *args, **kwargs):
        task_id=kwargs['task_id']
        aresult = AsyncResult(task_id)        
        context={}
        context['task_id'] = aresult.id
        context['task_state']=aresult.state
        context['task_result']=aresult.result
        return HttpResponse(f'task_id:{task_id}, status : {aresult.state}, get:{aresult.result}')

02_first_step_with_django/example/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>task_id : <p>{{task_id}}</p></div>
    <a href="{% url 'myapp:task_result' task_id %}">go to result</a>
</body>
</html>

02_first_step_with_django/example/templates/myapp/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>task_id : <p>{{task_id}}</p></div>
    <div>task_state : <p>{{task_state}}</p></div>
    <div>task_result : <p>{{task_result}}</p></div>
</body>
</html>